### ISSUE TITLE
todo : 2-integrate /2-integrate 

### ISSUE THREAD

**Issue by ervinMamutov** [ervinMamutov/bf-separation-of-concerns#3]
- [x] create branch `2-integrate`
  - [ ] 01-add-event-listener
  - [ ] 02-read-write-dom
  - [ ] 03-event-delegation
  - [ ] data-in-array
  - [ ] data-in-object
